### ISSUE TITLE
Backbone Custom Builds

### ISSUE THREAD

**Issue by gfranko** [jashkenas/backbone#1598]
I thought a great upgrade for a Backbone 1.0 release would be to split all Backbone Modules (Events, Model, View, Collection, Router, Sync) into separate files and provide users with the ability to make custom builds with a build tool such as Grunt and/or DownloadBuilder.js.  What do you think?  If you are interested, I would do some work and issue a pull request.

**Comment by DylanPiercey** [comment]
It would be nice if we were to switch to browserify or webpack, that way we would have the best of both worlds (multiple files and a single file) easily.

**Comment by ogonkov** [comment]
It's would be nice to have `Events` as separate module. Quite useful when builds custom modules with optional `Model`s and `Collection`s dependencies.

**Comment by Zarlex** [comment]
I'm using the Backbone Model and Collection in my Angular and AngularJS projects. I only need the model and the collection because the concept the concept is awesome. I'm using is as the data access layer. Angular is providing the ui layer.

I  recently wrote an article about how you can benefit from using BackboneJS in an Angular app: https://docs.google.com/document/d/1ptYmQzjq8EWLKyqFENqyXwzz67VNWzh_-clhy4W5R40

It would be really nice to split BackboneJS into several components to you can include only the stuff that you need.

@jashkenas What about splitting the src files into multiple files and let a build task concat them into one file so you have both: 
 - a simple single file
 - and split up source files
?
