### ISSUE TITLE
Model.fetch options.success vs. options.error callback signature mismatch?

### ISSUE THREAD

**Issue by jedrichards** [jashkenas/backbone#2971]
In the docs it says:

> [Backbone.Model.fetch] ... Accepts success and error callbacks in the options hash, which are both passed (model, response, options) as arguments.

But as far as I can tell the success callback has a signature like this:

```
function success (model,responseJSON,options) { }
```

And the error callback looks more like:

```
function error (model,jqXHR,options) { }
```

What's going on? It seems like they are passed different sorts of parameters compared to what the docs claim?

**Comment by AL-X-dev** [comment]
Except that now, there is a second place where "options.error" is executed, and it has an entirely different function call signature.  On version 1.3.3 of "backbone.js" these are lines 1452 - 1458; occurring just before the end of the "sync()" function.  This seems wacko -- two different signatures for the same function.  I am having major difficulties because of it.  Here is code:

    // Pass along `textStatus` and `errorThrown` from jQuery.
    var error = options.error;
    options.error = function(xhr, textStatus, errorThrown) {
      options.textStatus = textStatus;
      options.errorThrown = errorThrown;
      if (error) error.call(options.context, xhr, textStatus, errorThrown);
    };
