### ISSUE TITLE
Renaming the ID to _id because of CouchDB

### ISSUE THREAD

**Issue by binarykitchen** [jashkenas/backbone#302]
Hello again

Because the CouchDB stores the IDs under the name '_id' I have to map every ID in Backbone models to _id and reverse which is annoying and a waste of bandwidth.

Is there a way tho configure the name of the ID attribute for all Backbone models?

**Comment by costa** [comment]
I've just stumbled upon this and I agree with @cthorne66 and @binarykitchen — this should be fixed in the core, and `#toJSON` should be overridden the other way around — if needed (which shouldn't be really). As of this moment, `idAttribute` is a half-assed *surprising* functionality.
I would open this for discussion if in doubt — this shouldn't break things for sane people, and the rest should adjust.

**Comment by costa** [comment]
Two weeks passed and my comment above doesn't seem relevant anymore. Huzzah!
