### ISSUE TITLE
Object.observe() integration

### ISSUE THREAD

**Issue by dhenson02** [jashkenas/backbone#3231]
Since **`backbone.js`** is largely built on listening to views, models, collections and other objects (in its own way), the utilization of `Object.observe()` (thanks to Chrome's 36 stable release) can now be reasonably implemented as a much more manageable and performant *(which I'm being told isn't a word)* alternative to the underlying `.get()` / `.set()` methods we've all come to know and love.  

I'm not proposing to completely do away with anything.  Simply, given the presence of an `Object.observe()`-capable browser, utilize **it** instead for listening to (and updating/deleting) objects.

I've looked everywhere for discussion on this topic and it doesn't seem to be on anyone's public posts or pages.  I even found a couple of **`backbone.js`** add-ons but they're well over 2-3 years old and inactive.  However, if I have overlooked something (even something in the master branch here), please point me in the right direction and this issue can be closed.

Thanks.

PS - I would love to take this on with a pull if it isn't already being worked on but I don't want to duplicate anyone's current work if I can avoid it.

**Comment by arshabh** [comment]
This thread has been lying dead for a long time now. Any identifiable area that we can start working upon?

**Comment by jashkenas** [comment]
You're right. It is pretty dead. So let's close it, and look forward to the pull request, whenever such a thing appears.

**Comment by mbrevda** [comment]
One thing that should be discussed before anyone starts implementing this should be the location of a model's properties. I see three options"

A. The models attributes stay under `model.attributes` and the observer proxies calls from the model to `model.attributes`: the results would be an unsymmetrical api where properties can be set with `model.prop = foo` but only gotten with `model.get('prop')`.

B. Model properties are set directly on the model object: changing the location of attributes can potentially introduce chaos to anyone that might have been relying on them until now. 

C. Adding the observer to `model.attributes` directly: would allow for a symmetrical api, but it seems rather counter intuitive to have to call `model.attributes.foo = 'bar'`

Thoughts @jashkenas ? Is there an elegant way to move properties directly to the model, whilst not affecting all the internal `_properties` that currently exists?

**Comment by jashkenas** [comment]
It's probably not elegant to migrate, but we should work towards with the ideal API — not a compromised one.

Try putting the attributes directly on the model object, and see how it feels.

**Comment by jridgewell** [comment]
> Try putting the attributes directly on the model object, and see how it feels.

:+1:. Every server-side framework I've ever used places attributes directly on the model with attribute specific getters and setters. It'll be a breaking change, but it's a good one.

**Comment by mbrevda** [comment]
I like that! Thanks for the feedback.

So why was attributes originally used? I understand the need for using getters/setters so that BB knows when to trigger events. But why `attributes`? And if the data is directly on the model, how do we know what is an internal properties (say `cid` or `_events`) and what should be returned in when `toJSON()` is called?

**Comment by lukeasrodgers** [comment]
Unless I'm misunderstanding the proposal, it strikes me that javascript doesn't provide the same facilities that some other languages do that would help avoid property/method naming conflicts that would likely arise from "putting the attributes directly on the model object."

**Comment by jridgewell** [comment]
> javascript doesn't provide the same facilities that some other languages do that would help avoid property/method naming conflicts

Nor does Ruby, but Rails has successfully done it.

> So why was attributes originally used?

I think it's for easy bookkeeping (think `#toJSON`, `#template` being just passed `this.model.attributes`, etc...)

**Comment by lukeasrodgers** [comment]
I think I am misunderstanding your suggestion, because ruby definitely does have what I have in mind: an object can have a method named `foo` and an instance variable named `foo`. A javascript object can't have a method named `foo` and a property named `foo` without a conflict, AFAIK (I am not totally up to date on all the latest js improvements/proposals).

**Comment by mbrevda** [comment]
@lukeasrodgers it would seem so; there is no, say `_get()` a la php.

@jridgewell the quesiton was mostly rhetorical, its obvious why it was there. The question is how to deal with it moving forward

There are many interesting ideas worth exploring (although not all are viable at this time due to browser support). For example, whilst not providing much as far as performance improvements, using [es6's Proxy method](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) would allow for `model.foo = 'bar'; model.foo/*bar*/` with minimal changes to the current backbone (and leaving the `attributes` stuff intact). At this time, Proxy support is limited to [FF only](http://kangax.github.io/compat-table/es6/#Proxy) ([partly imlemented in chrome](https://code.google.com/p/v8/issues/detail?id=1543), behind a flag, although development seems rather stagnant/low priority)

*I think* that the greater goal here though is to have the **most minimal** amount of boilerplate around native objects and to utilize native features instead of implementing them in backbone. The point of this discussion is to figure out if that is the direction the project wants to move in. To that end, there might be room to minimize a lot of BB's code/complexity - along with the objects 'helper' properties (`_changed`, `attributes`, etc). [Object.observe](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) nativly returns much of the data that BB works hard to keep track of, like the `type` argument which can make event triggering simpler (it returns "add", "update", or "delete") and `oldValue` which *I think* would elminate the need for `_changing`, `_previousAttributes`, and `changed`. Due to it's async nature, `_pending` might also become redundant - making the 'helper properties' almost totally redundant (the black sheep in this list is `cid`).

In that case, BB can be whittled down to a model being a simple object (w/ some helpers on the prototype) and collections being a simple array of objects (again, with some helpers).

In the greater picture, due to the async triggering of events, this can lead to waaaaay faster event triggering and view re-rendering, but also to greater complexity do to the entire client side becoming one huge async app.

So lets throw promises in the mix while we're at it! /s

**Comment by jridgewell** [comment]
> I think I am misunderstanding your suggestion, because ruby definitely does have what I have in mind: an object can have a method named foo and an instance variable named foo.

Sorry, what I mean is the methods are always just getters and setters for the property. IE, `model.foo = :foo` in Rails is really a setter being called. If we ignore specialized getters and setters and just perform the simple case, then they are the same. `Object.observe` can then trigger the specialized properties for setters.

> The question is how to deal with it moving forward

The only way I see this working is keeping a list of `attributes` still around. Say `this.attributes = ['foo', 'bar', 'baz']`. Then `#toJSON` knows to `_.pluck(this, this.attributes)`, rendering can pass just pass the model (which gives you access to `#escape`).

**Comment by mbrevda** [comment]
I see your point @jridgewell, there will always be potential for conflicts, and thats just how js works (`var x = {forEach: 5}; x.forEach(done)` :bomb:).

Should we take extreme steps to protect the user from that (by forcing getters and setters, and stopping them if an internal property is about to be overwritten) or should we recede to a more native approach and leave the problem of conflicts to the user's discretion.

**Comment by jridgewell** [comment]
> Should we take extreme steps to protect the user from that (**by forcing getters and setters, and stopping them if an internal property is about to be overwritten**)

Doesn't that lead us back to what we have now? I think this'll only be a problem in the beginning. After that, it'll seem obvious.

- - -

I'm really excited that you're thinking over all the possibilities here.

**Comment by mbrevda** [comment]
> I think this'll only be a problem in the beginning
So you agree that we should go back to the basics and set attributes directly on the object?

**Comment by jridgewell** [comment]
Yup.

**Comment by mbrevda** [comment]
Great, will give this more thought.

**Comment by mbrevda** [comment]
Object observe is a really interesting update to the js platform. It seems to be a simple, clean way of responding to events with minimal fuss. I have some code in place, I hope to be able to share it soon. In the mean time I was hoping to gather some feedback:

 1. How might you feel/react if, say, backbone remove the ability to silence events (i.e. `this.set({foo: 'bar'), {silent:true})`), instead triggering an event on every single change?
 2. Assuming your reaction to the above was negative, how would you react if you had to manually "disable" events instead of passing them inline? Here is an example of what that might look like:

```js
this.disableEvents()
this.set({foo: 'bar'})
this.enableEvents()
```

Thanks!

**Comment by akre54** [comment]
If you still have to use setters for this to work, what's the advantage of Object.observe?

**Comment by mbrevda** [comment]
"have" is the key word here. If you **must** have fine grained control over event dispatching, then o.o might not be the right choice for you. Hence my question is: dose a project like backbone "have" to have fine grained event transmission control?

**Comment by filipmares** [comment]
i wouldn't lose sleep over not being able to pass in "silent: true". It
always felt like a dirty option to me. 😀

**Comment by dgbeck** [comment]
Its dirty but its pretty damn important.

**Comment by mbrevda** [comment]
@filipmares not being able to silence event would results in a hell of a lot of events being fired (see the source for construct/add/fetch just to name a few). But @dgbeck - can you expound more on why that would be a bad thing?

**Comment by akre54** [comment]
Seems to me the advantage of O.o is that you can do `model.title = "bar"` rather than going through setters and an intermediary `attributes` object. Otherwise what's the point?

I have no love for `{silent: true}` but I'm not convinced Object.observe is the answer either. There's a great deal of redundancy between the innards of Backbone and O.o that I don't think we actually need to reconcile. It's fine if they live on as separate approaches.

Regardless, in my experience people seem to be moving away from the observer pattern that Backbone, Angular, and O.o promote in favor of the immutability / virtual DOM model of React these days. It's just too much bookkeeping.

**Comment by dgbeck** [comment]
Its hard to nail down what the exact circumstance `silent : true` is necessary, but I'm confident there is some unfortunate contour of reality that requires it to be available. There might be a convincing argument related to circular reactions to events.

I do remember some discussion about its elimination in the past and a subsequent agreement that it did need to be left in. I don't think it is something that can be brushed under the table.

**Comment by mbrevda** [comment]
@dgbeck Not having a silent option really leads to some interesting challenges, even with pure js (paste this in your console: `var o = {};Object.observe(o, function(e){e[0].object.x++});o.x=0`) - but challenges can be overcome. Having a silent option *might* be important, but that doesn't mean that its absence will be catastrophic. Off the top of my head, I can offer [run-once methods](http://underscorejs.org/#once) as a partial solution - I'm sure there are other ways, too.

@akre54 at first glance, you are correct that "all o.o offers is `model.foo = 'bar'`", but in truth thats not what o.o is about. In fact, directly setting/getting properties can be achieved in about 25 lines of code with no internal plumbing changes to backbone at all, using es6's new [`Proxy`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object. With Proxy, an object-wide (property agnostic) getter/setter can be used, and have gets/sets "proxied" to some other object (in our case `this.attributes`).

The way I see it, o.o is mostly about raw speed. Check out [this naive test](http://jsperf.com/backbone-events-vs-oo#run) of responding to events in backbone vs o.o (I tried adding a polyfill for firefox, got weird results, so focus on Chrome for now), in some iterations o.o is 5x faster!

Finally, when dealing with performance, and especially dom performance, I believe the elephant in the room is virtualdom/react.js. I'll expand more on that in another comment, but for now just one point: correct me if I'm wrong, but don't react state changes need to be triggered somehow? Also, react.js don't seem to have much in place as far as data handling/manipulation. That leaves a desire for backbone-esque library that can act as a transient data store/manipulation/persistence layer, triggering events when data changes, and having react.js (or whatever) update on said events. tl;dr: react.js is about the view, there is still a need to deal with the actual data.

**Comment by mbrevda** [comment]
@akre54 rereading [your comment](https://github.com/jashkenas/backbone/issues/3231#issuecomment-88611498), I realized that my code example wasn't clear. I wasnt suggesting that setters will be needed, I was just trying to illustrate what backbone might look like if silent could not be passed, and one wanted to disable events another way.

**Comment by akre54** [comment]
@mbrevda thanks for clarifying. Interesting discussion but we seem to be getting off topic a bit here. Mind if we move to gitter or the mailing list?

**Comment by mbrevda** [comment]
In case anyone was still hopeful, seems this is officially not happening: [Object.observe removed from TC39](https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html)

**Comment by HenriqueSilverio** [comment]
:+1:
