### ISSUE TITLE
Backbone.Collection will not trigger "invalid" event

### ISSUE THREAD

**Issue by s-murata** [jashkenas/backbone#3328]
If a collection create a new model that has a `validate` property and invalid attributes, the collection don't trigger `invalid` event.

`_prepareModel` method always return a new model and not return `false`, because a new model's `validationError` attribute is `null` by default.

use `.isValid()` method, instead of `validationError` property.

```
$ diff -u backbone.js.org backbone.js
--- backbone.js.org  2014-10-01 15:07:00.925991648 +0900
+++ backbone.js 2014-10-01 15:07:53.708991655 +0900
@@ -943,7 +943,7 @@
       options = options ? _.clone(options) : {};
       options.collection = this;
       var model = new this.model(attrs, options);
-      if (!model.validationError) return model;
+      if (model.isValid()) return model;
       this.trigger('invalid', this, model.validationError, options);
       return false;
     },
```

**Comment by yamsellem** [comment]
+1

**Comment by mice530** [comment]
+1

**Comment by platinumazure** [comment]
Not that I disagree with where this is coming from, but I'm wondering if this was an intentional thing? Like, if the goal is to require `{validate: true}` on things like `Backbone.Collection#add()`, then the code as is is fine. (Note that a `model.set` call occurs under the hood and `{validate: true}` would get passed along.

If that's the case, then switching to `isValid()` would force validation every time and give no one any choice in the matter.

I agree that the code is unclear in this case, though, and I would certainly like the docs to take a stance.

**Comment by jashkenas** [comment]
Yes. I think this is intentional for that reason. Just pass `validate: true` if you wish to validate at that time. The docs should make this clear.
