### ISSUE TITLE
URL inconsistencies

### ISSUE THREAD

**Issue by designermonkey** [jashkenas/backbone#3447]
Hello.

I've spotted a couple of inconsistencies with URL formats used in Backbone. Just wondering what thoughts are on resolving them.

In the Router, we are told to use urls with the pattern `url-path`, yet in Models, they have the pattern `/url-path`. Personally, my experience leans towards patterns with a preceding slash.

Is there any way that the differing patterns can be resolved?

**Comment by designermonkey** [comment]
I've found that at lt line `1289`, routes are converted into `Regexp`s. And in the History part, `rootStripper` is defined.

Could this `rootStripper` not be in use in the Router too, so pre or post slashes are optional?

The problem I've seen is that the History part can match routes with these slashes, yet they don't resolve to functions, as functions don't have slashes in them.

**Comment by designermonkey** [comment]
Defining `rootStripper` at line `1226` before the other regexs, and then adding a replace in at line `1290` does the trick.

I can send a PR if you'd like?

**Comment by braddunbar** [comment]
Hi @designermonkey! Thanks for pointing this out!

I see what you mean, but I think the problem is with conflating urls and fragments. Model urls are primarily meant for making requests to the server, while fragments are not necessarily an entire url and are meant only for client-side routing. That said, model urls *can* be used as fragments and this is enabled by stripping the leading slash. Hope that helps. :smiley:

**Comment by designermonkey** [comment]
Ok, so in order to make it more consistent across both areas, and use router fragments as urls as well, couldn't this tiny change be added?
