### ISSUE TITLE
Collection#create doesn't properly pass final options to success callback

### ISSUE THREAD

**Issue by carljm** [jashkenas/backbone#3478]
In https://github.com/jashkenas/backbone/blob/master/backbone.js#L986 `Collection#create` wraps the `success` callback (in order to handle `wait: true`). But the wrapper does not take the third argument, `options` -- when it calls the wrapped callback it instead just sends it the options `Collection#create` received. This breaks any custom sync code that might be modifying the options further downstream (for instance, it breaks https://github.com/nilbus/Backbone.dualStorage, which adds `dirty: true` to the options if the sync to server failed but succeeded to localStorage instead).

I don't know if this type of signaling via `options` is supported, but I can't see why it would hurt for the wrapper callback here to actually take the options the callback was called with and pass those along, instead of short-circuiting with the original options. Would a PR for this change be acceptable?

**Comment by platinumazure** [comment]
@carljm I opened #3488 to deal with this. Seems it works basically everywhere else that uses `sync` directly, but since `Collection#create` delegates to `Model#save`, its callback actually gets options.

Caveat: If `sync` changes `options` to point to a new object, that object will not and cannot (yet) propagate through, because `Backbone.ajax()` does not pass the options object to a callback. So that may need some thinking. But I believe #3488 fixes your issue-- please feel free to give it a try and let me know.

**Comment by carljm** [comment]
@platinumazure Thanks! That PR does fix my issue, though I think the only necessary change is really the addition of `callbackOptions` at https://github.com/jashkenas/backbone/pull/3488/files#diff-0d56d0d310de7ff18b3cef9c2f8f75dcR988 and following two lines. The rest of the PR looks to me like entirely cosmetic changes (though I'm not an experienced Backbone dev so I'm probably missing something); I don't see the reason for adding the new `wait` vars everywhere.

**Comment by platinumazure** [comment]
@carljm You're right that there's only one real necessary change. But I wanted to add tests around the others. Re: why add `wait` variables: If we want to (in general) allow `Model#sync`, `Backbone.sync`, or `Backbone.ajax` to modify the options object, we need to make sure `options.wait` is not modified between when the asynchronous call starts and when it fires the success callback. Otherwise we could get really weird behavior (for example, attempting to `add` a model to a collection twice on `Collection#create()`).

**Comment by carljm** [comment]
@platinumazure Ah, I get it! Makes sense. Thanks for the fix!
