### ISSUE TITLE
model.destroy() breaks collection.each

### ISSUE THREAD

**Issue by fastest963** [jashkenas/backbone#3534]
```JS

  test("destroy models in each loop", 4, function() {
    var collection = new Backbone.Collection([{id: 1}, {id: 2}, {id: 3}, {id: 4}]);
    collection.each(function(model) {
      notStrictEqual(model, undefined);
      if (model !== undefined) {
        model.destroy({url: function() {}});
      }
    });
  });
```

That test breaks because `model.destroy` fires `destroy` which causes the collection to call `this.remove(model)` which then splices out the array and causes the `each` to break. This technically could be considered a bug in lodash/underscore (@jdalton ?) but released versions of those cause this so we might want to fix it in backbone.

Deferring the `coll.remove` seems like a bad idea so maybe we should just slice the models into a new array when calling `_.each` and `_.forEach`. We could also make `model.destroy` just do all the destroying in a defer?

Let me know what you guys think.

**Comment by fastest963** [comment]
A user can achieve this by instead doing:
```JS
var models = coll.remove(coll.models);
_.each(models, function(model) {
  model.destroy();
});
```

That's how I'm going to fix Grooveshark's code but we should consider either warning about this bug or fixing it since its definitely not obvious it's going to break.

**Comment by mr47** [comment]
@fastest963 The best solution is create a bulk update, and remove request on server, ```Backbone``` you dont need make N request for delete (N in ```Backbone.Collection```).

But if you want do this for a not synced ```Backbone.Collection``` how you writed.

**Comment by akre54** [comment]
Agreed. You shouldn't be doing this inside an each loop, that's just asking for trouble.

**Comment by earl3s** [comment]
I agree this should be addressed.  In my situation I wanted to change the remove the models without doing any server changes because I was resetting the collection to an original state.  This quirk threw me for a bit before landing here.

**Comment by Zarlex** [comment]
I ran into the same problem today and i also think this issue should be addressed or at least mentioned in the documentation. 
We have overwritten the default backbone sync method to set the option`{wait: true}` by default and everything was running smoothly because in this case
```
collection.each(function(model){
 model.destroy();
});
```
is working fine becasue it removes the model from the colelction when the server has confirmed the delete. 
However, we removed the flag `{wait:true}` recently and all cases were we added the possibility to delete multiple entries were broken.

It took a lot of time to find out that this is a backbone core issue

**Comment by Zarlex** [comment]
What do you think of the following solution:
Instead of delegating to the each method of underscore the collection could provide a own implementation and do this:
```js
var Collection = new Backbone.Collection.extend({
  each: function(callback, ctx){
    _.pluck(this.models, 'cid').forEach(function (cid, index) {
      var model = this.get(cid, index);
      callback.call(ctx, model, index, this.models);
    }.bind(this));
  }
});

var collection = new Collection([{id:1},{id:2}]);
collection.each(function(model){model.destroy()}
```
By creating an array with all the `cids` of the models that are in the collection and iterating over this instead of the model array there won't be any "concurrent modification errors" when deleting items.
The model lookup inside the `forEach` should be fast because it is just look up. The collction is storing all model cids in the `_byId` object

**Comment by jashkenas** [comment]
This isn't really a quirk, and has been discussed before in the past — it's the same thing as looping through an array with a `for` loop, and removing items as you go. The loop changes under your feet and breaks. It's just a normal programming thing.

Common solutions are to either iterate through your models backwards, or to store them in a separate array than the one you're modifying for the purposes of looping.

Of course, the *correct* answer is to do a bulk delete, and a Backbone collection.reset().

**Comment by Zarlex** [comment]
Yes i know that it is not really a quirk. The thing is that you can easy forget about it, especially programmers that are not too experienced. 
With the solution that i proposed you can just iterating over the collection and do what ever you want.
When doing REST calls sure a bulk delete request is the best. But there are also cases where you want to remove models from the collection without making any request. You always have to implement something like proposed in [this stack overflow thread](http://stackoverflow.com/questions/10858935/cleanest-way-to-destroy-every-model-in-a-collection-in-backbone).

My proposal could be improved when storing the `cids` of the added models in an extra object.
So instead of storing it in `_byId` you could store it in `_byCid`. And the you could just iterate over this object

```js
each: function(callback, ctx){
    var index = 0;
    for(var key in this._byCid){
      if (this._byCid.hasOwnProperty(key)) {
         callback.call(ctx, this._byCid[key], index++, this.models);
      } 
}
```
It is just a proposal to get rid of the trap where you can easily step into
