### ISSUE TITLE
route parameter passing order problem

### ISSUE THREAD

**Issue by SerkanSipahi** [jashkenas/backbone#3561]
###### HTML Links
I dont know if this a issue or not ! As you can see i have a optional paramter `:endCity`. Search1 passed the arguments correct, also second parameter is null. That is what expect but the Search2 is not what i expect. See below my code example and logs.

```html
<a href="search/sfo/18.05.2015/06.06.2015/2">Search 1</a>
<a href="search/sfo/18.05.2015/06.06.2015/2/1">Search 2</a>
<a href="search/sfo/mfb/18.05.2015/06.06.2015/2">Search 3</a>
<a href="search/sfo/mfb/18.05.2015/06.06.2015/2/2">Search 4</a>
```

###### Router-Config
```json
{
    "search/:startCity(/:endCity)/:startDate/:endDate/:adults(/:children)": "search",
}
```

###### Log
```
Search1 = sfo null 18.05.2015 06.06.2015 2 null null // correct

Search2 = sfo 18.05.2015 06.06.2015 2 1 null null // wrong, second parameter must be null
Search2 = sfo null 18.05.2015 06.06.2015 2 1 null // that is what i expect

Search3 = sfo mfb 18.05.2015 06.06.2015 2 null null // correct
Search5 = sfo mfb 18.05.2015 06.06.2015 2 2 null // correct
```

I hope you can help me

**Comment by braddunbar** [comment]
Hi @SerkanSipahi! Thanks for letting us know about this. Unfortunately, the expected result is not something a route string can discern. The regular expression used to match an optional parameter doesn't know the difference in a city and a date so it will assume the second parameter matches the first optional path segment if there are enough of them.

From my perspective you have two options:

1. Use a regular expression route. This isn't elegant, but will allow you direct control over what each optional segment matches.
2. Use query string parameters. It looks like these are really modifiers to the `search` route, so it would be nice semantically. Also, you won't have to worry about matching since you can let a query string parser do the hard work.

Hope that helps!

**Comment by SerkanSipahi** [comment]
@braddunbar 
1.) "regular expression" is not what we want
2.) we use "query string parameters" for something different.

The idea was, if someone make a search sfo to sfo we build a string like `search/sfo/18.05.2015/06.06.2015/2` and not `search/sfo/sfo/18.05.2015/06.06.2015/2`. But in this case(issue etc) we have no other choice !  The optional parameters must always be specified in our case.

Thank you.
