### ISSUE TITLE
CORS issue (Yet again)

### ISSUE THREAD

**Issue by sabzo** [jashkenas/backbone#3565]
My apologies if this is a newbie question: Inside my Backbone View I'm able to Make regular Ajax HTTP calls just fine, I'm calling a CORS enabled server. However, when I use any of Backbone's .save or .create methods I can't access my API.

How can one enable CORS support in backbone once and for all?

**Comment by NickNaso** [comment]
I think that the problem is not backbone. You have to enable CORS for support POST and PUT call on your API most probably you can execute only GET call. But you check this by calling your API using Ajax HTTP or Postman https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm. When you call create method backbone execute a POST call to your api endpoint so please check if your server permit this type of call. What kind of server do you use?

**Comment by sabzo** [comment]
I see. I have a Python App running behind Gunicorn. When making a POST or PUT on my API using HTTPie or Postman I'm getting the expected headers, for example:

Connection → close
Date → Sun, 12 Apr 2015 16:13:31 GMT
Server → gunicorn/19.2.0
access-control-allow-headers → Content-Type
access-control-allow-origin → *
content-length → 70
content-type → application/json; charset=utf-8

Also running a simple Ajax call within my app I get an expected response:

$.ajax({
        type: 'POST',
        url: "http://localhost:8000/api",
        data: {'hi' : 'newPersonName'},
        success: function(data) {
          console.log(data);
        },
        error: function(data) {
          console.log(data.status)
          console.log(data.statusText);
          console.log(data.responseText);
        }
       });

What troubles me is if it's a true CORS issue then all Ajax calls would be restricted, however the Backbone Ajax call is the only one being restricted.

**Comment by NickNaso** [comment]
i'm using Backbone 1.1.2 Underscore 1.7 and jQuery 2.1.3 and my server is an expressjs app configured for cors and all is fine. The only thing that you can try is to override Backbone.sync to set cross domain:
```javascript
Backbone._sync = Backbone.sync;
// override original sync method to 
Backbone.sync = function(method, model, options) {
	options || (options = {});
        if (!options.crossDomain) {
            options.crossDomain = true;
        }
	return Backbone._sync(method, model, options);
};
```
Which is the response when you call save method or create?

**Comment by sabzo** [comment]
The response I keep getting is: "XMLHttpRequest cannot load ... No 'Access-Control-Allow-Origin' header is present on the requested resource." To make sure it's not a server issue I'm even calling the Instagram API: https://api.instagram.com/v1/media/popular?client_id=MY-CLIENT-ID-HERE and within my Backbone I get the CORS. But in Postman I don't get the CORS.

**Comment by jridgewell** [comment]
@sabzo: Can you post a working jsfiddle with the minimum code needed to reproduce?

**Comment by sabzo** [comment]
@jridgewell 

Thanks for bearing with me, and people such as myself:
I haven't used jsfiddle but I've tried to duplicate a simple Backbone.Model.save to a sample EC2 server I just threw up for the demo:

https://jsfiddle.net/sabzo/ahqf6xwv/5/

Thanks.

**Comment by NickNaso** [comment]
Hi @sabzo  i think to understand your problem. I edited your client code as reported below:
```javascript
 var MyModel = Backbone.Model.extend({
        urlRoot: 'http://ec2-54-149-67-254.us-west-2.compute.amazonaws.com/video',
        defaults: {
            "title":"t1",
            "legend": {
                "actors": ["a1","a1a", "a1b"],
                "directors": ["d1, d2"],
                "region": ["California", "Cuba"],
                "language": ["English", "Spanish"],
                "mood": ["Adventure"],
                "category": ["Action"]
            },
            "description": "desc1",
            "src": "s1",
            "trailer":"t1",
            "img":"i1"
        }
    });

    var m = new MyModel();

    m.save(m.toJSON(), {
       success: function(model, response, options){
           console.log("SUCCESS");
           console.log(model);
           console.log(response);
       },
       error: function(model, response, options){
           console.log("ERROR");
           console.log(model);
           console.log(response);
       }
    });
```
I get this error as reported in the image below:
![cors](https://cloud.githubusercontent.com/assets/387506/7125234/78494664-e22f-11e4-858a-8e4979d6651d.PNG)

This error happen because when you make CORS request the browser execute a preflight request similar to this:
OPTIONS http://ec2-54-149-67-254.us-west-2.compute.amazonaws.com/video 
Your server have to respond to this request setting header as reported below:
'Access-Control-Allow-Origin', '*'
'Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE'
'Access-Control-Allow-Headers', 'Content-Type, Authorization'
and send a 200 as status response.
You can find some technical documentetion about that here:
http://enable-cors.org/index.html
Here there is a node example:
https://gist.github.com/cuppster/2344435
Hope to be a help.

**Comment by sabzo** [comment]
@NickNaso Grazie Mille!!

I'm now very sure this is a server issue. I was able to observe the pre-flight while testing on Firefox. In Chrome I couldn't see the pre-flight headers, but on Firefox I saw that the OPTIONS method was being sent and my server wasn't responding appropriately to that.

Thanks a bunch.
