### ISSUE TITLE
Uncaught Router crashes at decodeURIComponent

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [jashkenas/backbone#3569]
Router crashes with URIError: URI malformed on users copy-pasted input like this 

```
Внесите изменения в алгоритм, приведѐнный в задаче 2, таким образом, чтобы мама предусмотрела следующие ситуации, когда: а) в холодильник%D0%
```

Often found at the search routes.

**Comment by braddunbar** [comment]
Hi @QiV! Thanks for the issue and the pull! :smiley: 

If I understand correctly, when the parameter is malformed (contains invalid percent encoding) you'd like to get it back as is. Is that right?

**Comment by braddunbar** [comment]
Actually, I guess you want to decode the valid encodings and leave the invalid ones alone?

**Comment by QiV** [comment]
Yes, i would like to decode url as close as possible

**Comment by QiV** [comment]
Another way is to catch this error above router instance. But it is not so graceful.

**Comment by jridgewell** [comment]
I think this is handled by #3434?

**Comment by braddunbar** [comment]
> I think this is handled by #3434?

Nah, this one's separate. #3434 handles double decoding of `%25` via first `decodeURI` and then `decodeURIComponent`. This is about invalid percent encoding from user input.

**Comment by jridgewell** [comment]
In that case, we could mix in `invalidPercentOctets` from #3506 into `#decodeFragment`?

**Comment by braddunbar** [comment]
I like that idea, but that regular expression doesn't cover all the bases. For instance, it fails on the url presented by @QiV above.

```js
/%(?![a-fA-F0-9]{2})/.test('%D0') // false
decodeURIComponent('%D0') // throws malformed uri error
```

Is there a more restrictive test we can do?

**Comment by jridgewell** [comment]
Damn, I thought the issue was the trailing `%`.

We'll need to implement https://encoding.spec.whatwg.org/#utf-8-decoder as a regex.

**Comment by jridgewell** [comment]
Well, that was more fun than it should have been. I've [forked](https://github.com/jridgewell/regenerate) [mathiasbynens/regenerate](https://github.com/mathiasbynens/regenerate), made it take single hex code points, and yada yada.

```javascript
var encodedPercent = '(?:25)';
var invalidSingleOctet = '(?:[89abAB][0-9a-fA-F]|[cC][01])';
var invalidDoubleOctet = '(?:([cdCD][2-9a-fA-F]|[dD][01])(?!%[89abAB][0-9a-fA-F]))';
var invalidTripleOctet = '(?:[eE]([1-9abcefABCEF](?!%[89abAB][0-9a-fA-F])|0(?!%[abAB][0-9a-fA-F])|[dD](?!%[89][0-9a-fA-F])))';
var invalidQuadOctet = '(?:[fF]([1235-9a-fA-F](?!%[89abAB][0-9a-fA-F])|0(?!%[9abAB][0-9a-fA-F])|4(?!%8[0-9a-fA-F])))';
var invalidPercentsEncodings = new RegExp('%(' + [encodedPercent, invalidSingleOctet, invalidDoubleOctet, invalidTripleOctet, invalidQuadOctet].join('|') + ')', 'g');
function decodeFragment(frag) {
  return decodeURI(frag.replace(invalidPercentsEncodings, '%25'));
}
```

**Comment by akre54** [comment]
This is really the kind of change that should live in userland if needed (and props to @braddunbar for [the foresight to expose decodeFragment](https://github.com/jashkenas/backbone/pull/3434#discussion_r22464422)).

@jridgewell is there a nice one-liner someone can use to drop regenerate right into Backbone.history?

**Comment by jridgewell** [comment]
Without rewriting `decodeURI()` ourselves to not throw, there's no easy fix. I used regenerate because it had a syntax for already making hex regexs, but it isn't really feasible give to devs.

I'm actually forking [mathiasbynens/utf8.js](https://github.com/mathiasbynens/utf8.js) to rewrite percent decoding now. I should be able to reimplement `decodeURI` using it, and give it out to devs so they override `#decodeFragment`:

```javascript
var Router = Backbone.Router.extend({
    decodeFragment: require('decode-uri')
});

// ...
```

**Comment by braddunbar** [comment]
While I like the idea, I don't think we should re-implement `decodeURI` or `decodeURIComponent`. What would we do with the invalid encodings? Throw them away? Take a guess?

I think the common case is to expect well formed urls, including percent encoding. That said, I would rather we make it a bit easier to deal with those errors.

**Comment by jridgewell** [comment]
> While I like the idea, I don't think we should re-implement decodeURI or decodeURIComponent.

Oh no, this definitely wouldn't be Backbone code. Since `#decodeFragment` has been exposed, it be really simple to define your own `decodeURI`.

**Comment by dtipson** [comment]
Something like this seems to work for me, just before starting the history:

```javascript
    Backbone.History.prototype.decodeFragment = function(fragment) {
        try{
            fragment = decodeURI(fragment.replace(/%25/g, '%2525'));
        }catch(e){fragment='';}
        return fragment;
    };
```
Though I suppose just throwing away the entire prop would be better in some use cases?

fwiw, React seems to have the same behavior wherein a malformed url parameter, even one not relevant to the router or the application, will prevent the entire application from working: https://www.khanacademy.org/?more_like_crash_academy=%DF

On the other hand, I lean towards the consensus here that bad urls are bad urls and so not _really_ bugs, and handling them in certain ways is sort of up to the particular needs of the application (though an otherwise blank page with "malformed url" on it is probably not a great fallback: https://trello.com/?badparam=%DF ).

In addition to search strings that might end up in the url, I've seen this in the case of 3rd party mailing programs generating email links to BB applications that are including incorrectly encoded params.

**Comment by jgonggrijp** [comment]
@Kuznetsov-Ilia Was this issue fixed?

**Comment by Kuznetsov-Ilia** [comment]
@jgonggrijp No. As I see from the discussion above the problem is not in backbone source code, so no reason to keep this ticket opened.
