### ISSUE TITLE
View Events Property Problem

### ISSUE THREAD

**Issue by LordMidi** [jashkenas/backbone#3620]
I've updated our project and noticed a different behaviour. With the update from 1.1.2 to 1.2.0 I can't set the events property of a view in the "initialize" function anymore - or at least the callbacks don't get triggered. Do I set the events directly as the view property in the extend context it still works. But I need to create the selectors for the events dynamically, therefore I build the events property in "initialize".

Any ideas?

**Comment by jridgewell** [comment]
Ah, seems in all the commits for #3003, we removed the `#delegateEvents` call after calling `#initialize`.

As best as I can follow, it was [removed](https://github.com/akre54/backbone/commit/c5c0d2ef0c50be1468c470f48cf1b2fd6005b593) because of an early implementation of `#setElement` in that PR had to do [argument juggling](https://github.com/akre54/backbone/commit/986540f46f07d53257a293013938863f7b083a48), which wasn't the cleanest API. However, that implementation was [rewritten](https://github.com/akre54/backbone/commit/7180d5ce0ae68fa538ea0d1f278a2636bd403bc4), so I don't see why this can't be [supported again](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L1044-L1050). @akre54?

**Comment by akre54** [comment]
I think the relevant pull is #3060. You can also build the events in the `events` method:

```js
var View = Backbone.View.extend({
  events: function() {
    return getEventsFor(this);
  }
});

```

**Comment by jridgewell** [comment]
> I think the relevant pull is #3060.

:+1: Makes sense to me, just wanted to make sure this wasn't an oversight in #3003.

**Comment by jridgewell** [comment]
Also, you can use `#delegate` [directly](https://github.com/jashkenas/backbone/blob/1.2.0/backbone.js#L1271-L1273).

**Comment by marian-r** [comment]
I am extending Views with mixins dynamically inside the initialize method, which now does not work if some event handler is defined in mixin. Although, I'm OK with calling `delegateEvents()` method manually, it would be nice to document this BC break.

**Comment by akre54** [comment]
What do you mean mixins?

**Comment by marian-r** [comment]
As far as I know Mixin is a pattern when you insert functions from one object into another. Maybe I'm wrong about the naming. Situation with event handlers which I was talking about is the following:
```js
var myMixin = {
    eventHandler: function () {
        console.log("I'm from mixin");
    }
};

var MyView = Backbone.View.extend({
    events: {
        'click #myButton': 'eventHandler'
    },
    initialize: function () {
        _.extend(this, myMixin);
    }
});
```
In v1.2.0 `eventHandler()` is not registered as `delegateEvents()` is called before the view is extended with mixin.

BTW thanks for docs.

**Comment by akre54** [comment]
Ah. In that case you want to try and override the `prototype` instead of the instance (`this`).

```js
var MyView = Backbone.View.extend({
  events: {
    'click #myButton': 'eventHandler'
  }
});

_.extend(MyView.prototype, myMixin);
```

If you *really* need it (and you shouldn't need it). You can move the `_.extend(this, myMixin)` call into the `constructor` of your view. Think about why you're doing this though, and maybe opt to handle exceptional cases in the event handlers instead.

Or, as @jridgewell noted, you can delegate these events directly with `delegate`.

**Comment by marian-r** [comment]
I know about your solution, I'm using it in some places, but sometimes I need to choose the right mixin based on constructor arguments, so I'm extending instance with mixin in the `initialize` method and then calling `delegateEvents()` or `delegate()` as you wrote. You're right it can be done in `constructor()` method, but it has also some drawbacks which I don't remember at the moment.
