### ISSUE TITLE
$.Deferred is undefined after requiring Backbone >1.1.2

### ISSUE THREAD

**Issue by nucleartide** [jashkenas/backbone#3687]
Here's a [gist](https://gist.github.com/nucleartide/37caa96f15ceb0943385) of the problem. If you run install `npm install` with that package.json today, it'll install the latest Backbone which is version 1.2.1.

Strangely, `$.Deferred` is *only* undefined for versions of Backbone greater than 1.1.2. On Backbone 1.1.2, it works as expected and the console output is `[Function]`.

Anyone know what's going on?

**Comment by akre54** [comment]
It's because you're requiring in Backbone ([which requires in jQuery](https://github.com/jashkenas/backbone/blob/1.2.1/backbone.js#L26)) before you set up your window var.

If jQuery can't detect a global `document` variable, its `module.exports` value is a factory function that takes `window` as an argument: https://github.com/jquery/jquery/blob/2.1.4/src/intro.js#L25-L32

The simple answer is to move your Backbone require after your `global` setup. But you can also set `Backbone.$ = require('jquery')(window)` yourself.

**Comment by nucleartide** [comment]
Oh okay, thanks for the help!
