### ISSUE TITLE
this is just a question

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3706]
Dear Purveyors of Backbone:

Just a question for y'all. Why don't Backbone Views have the same defaults/attributes/options relationships that Backbone Models have? And, after checking the source, Collections and Routers don't either, why don't all Backbone components follow the same pattern? I am aware that the functionality of automatically assigning this.options was taken out of a newer version of Backbone, but the question I am asking is about a decision that was made long before that one.

Just curious, thanks

**Comment by akre54** [comment]
This type of question is better suited to one of the other channels (try the mailing list or the gitter board). 

The short answer is because they don't need to. Models are supposed to be where you care about stateful attributes that don't live on the object itself. In most cases just setting a property on your instance should be good enough.

That said, if you really need this in your app, I've written [a plugin](https://github.com/akre54/Backbone.Attributes) that allows you to borrow Backbone.Model's getter and setter functions for any object (including the rest of Backbone's classes). Check it out and see if that works for you.

**Comment by ORESoftware** [comment]
thanks will check it out
