### ISSUE TITLE
Backbone Truck Factor

### ISSUE THREAD

**Issue by gavelino** [jashkenas/backbone#3748]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Backbone** and obtained a value of **2**.

The developers responsible for this TF are:

Jeremy Ashkenas - author of 60% of the files
Brad Dunbar - author of 33% of the files

To validate our results, we would like to ask **Backbone** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Backbone**?

(b) Do you agree that **Backbone** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Backbone** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by RusAlex** [comment]
Suppose here are more than one key dev =)

**Comment by au-phiware** [comment]
Hello Guilherme,

Thank you for sharing your results with the Backbone community! A TF of 2 seems comparatively high considering that only 26% of the projects you considered scored higher :)

I would be interested to know which files from backbone were actually included in your analysis. I would have guessed that your 'file cleaning' process would have eliminated all but `backbone.js`, `test/*.js` and `examples/**/*.js`. Personally, I would be interested in what the results would be if you included documentation (which also includes the gh-pages branch) since the quality of the documentation can be a deal breaker when I'm deciding to make use of an FOSS project. On the other hand I can understand how it might skew the results since it actually takes a different set of skills to produce a high level of documentation and a project would not be incapacitated if all the copywriters got up and left.

It seems to me that the definition of *Degree of Code Authorship* is very limited. I admit I have not read Fritz et. al. but I challenge the idea that an FOSS project would become "incapacitated" if the "developers able to influence or command the implementation" ceased to do so. However, I think your results are accurate, @jashkenas was [recently refered to as a "God"](https://github.com/jashkenas/backbone/issues/3746#issuecomment-128375280) along with @jdalton! But I doubt that this revere of the original authors would be enough to bring an end to backbone if they decided to relinquish the reins, or even if they declared backbone a mistake and started anew! It appears to me that @jashkenas plays an executive role in recent times, I have been only watching this project for a few weeks but in that time he has only chimed in once with a [comment about documentation](https://github.com/jashkenas/backbone/pull/3735#issuecomment-125758718). Looking back on [his commit history](https://github.com/jashkenas/backbone/commits?author=jashkenas) the majority of recent commits have been merging PRs from other developers, notably @jridgewell, where did he rank in your analysis?

I think that, in backbone's case, this is a sign that the project has matured. It has reached that stage where the original authors transition from owners to stewards. FOSS projects are far from the anarchy that some people imagine them to be, in fact, strong and/or consistent leadership is very common (and arguably important). In fact, for a mature FOSS project, I would argue that *Truck Factor* is poorly named and that a lower score is better. I would hope that if @jashkenas and @braddunbar left the project then the community would quickly reorganise behind another one or two developers, but (and this the crux of my idea) not more.

Can you please expand on your methodology and how you deal with merges in your analysis? For example, to whom is commit ff57b54cbb1b1c0d297d25bf673c8adc7023dd69 attributed to? I suspect that your analysis attributes it to @jashkenas when, in my opinion, @jridgewell should be attributed. Indeed, git's own blame function, attributes the file changes to @jridgewell as the author of the commit that changed that file even though that file was in a different repository than jashkenas/backone.

Your paper, like any good research paper, raises more questions than it answers! I commend you on a job well done! :D

Cheers,
Corin.

**Comment by jdalton** [comment]
>  I would hope that if jashkenas and braddunbar left the project then the community would quickly reorganise behind another one or two developers, but (and this the crux of my idea) not more.

I think there's something else to consider. It's not just leaving the project but becoming less involved without a clear exit which can cause delays and decay. As a project lead's interests and priorities shift to other things you'll see releases start to lag. The contributors can create release issues and do much of the prep work but the lead hits the button.

**Comment by jashkenas** [comment]
To quickly answer your questions:

a) In terms of Bus Factor, no. It's about being the project's future if someone is hit by a bus today — not about historical development. If you look at the authors of recent commits, you'll see this: 

![image](https://cloud.githubusercontent.com/assets/4732/9342858/34c25cd6-45cc-11e5-9bba-b25853f15b0b.png)

b) So, no, Backbone will not be "in trouble" if I get hit by a bus, and Brad wins the lottery.

c) The most important characteristic that renders the Bus Factor moot is that Backbone is basically a finished project. Comprehensive documentation also helps, and even more important than that is the annotated source code.

Cheers.
