### ISSUE TITLE
Rethink backbone templates V2

### ISSUE THREAD

**Issue by mr47** [jashkenas/backbone#3772]
I found a pretty awesome idea [here](https://github.com/Rapid-Application-Development-JS/itemplate).
Using incremental dom with underscore templates its tiny and extremely powerfull.

Its faster that underscore templates and react too, in fact its using almost same idea like react, but this was developed by [google](http://google.github.io/incremental-dom/#passing-functions).

PS: Or at can be good idea for marionette ?

What do you think about this @jashkenas @megawac @jridgewell ?

**Comment by akre54** [comment]
There are many of these virtual DOM libraries out in the wild ([virtual-dom](https://github.com/Matt-Esch/virtual-dom) is a good one). Backbone has been and should continue to be agnostic to your choice of templating library.

**Comment by jridgewell** [comment]
I'm actually [intimately familiar](https://github.com/google/incremental-dom/graphs/contributors) with iDOM. One of the reasons I'm so enthusiastic about it is that there's really nothing that needs to be done to support it in Backbone. Just treat it like a normal `#template` method:


```js
var View = Backbone.View.extend({
  template: function(data) {
    // some iDOM code
  },

  render: function() {
    // some stuff...

    iDOM.patch(this.el, this.template, this.model.attributes);

    // some more stuff...
  }
});
```

**Comment by jridgewell** [comment]
@akre54: Sorry, I should have read your comment before closing. Please feel free to reopen if you want to keep this as a general tracker for support virtual DOMs.

As for my 2¢: View is the most un-opinionated class in Backbone (for better or worse). I only know of one practice we've codified that prevents general vDOM: diffs on the container may not keep the container

```js
// From virtual-dom's example code
var tree;
setInterval(function () {
      count++;

      var newTree = render(count);
      var patches = diff(tree, newTree);
      rootNode = patch(rootNode, patches); // (A)
      tree = newTree;
}, 1000);
```
Here, `rootNode` is reassigned every tick. With a normal Backbone View, it'd be natural to assume `rootNode` should be `this.el`. But it can't be (or else event delegation breaks), so it's actually the first child of `this.el`.

**Comment by akre54** [comment]
@jridgewell I admittedly don't have a ton of experience using vdom with Backbone, but from my experience with mithril and React one thing that stands out to me as a potential pitfall with your example is that it looks like it'd work great for a single view with only normal html elements, but how do you manage nested Backbone Views that way?

`render` in Backbone combined with Backbone classes work quite differently from most vdom libraries.

**Comment by jridgewell** [comment]
> how do you manage nested Backbone Views that way?

I treat it the same way I do subviews with jQuery: detach, render, reattach (that's why I left the two "do something" comments in the render method :wink:). Or you can rerender and `setElement`, but that's much slower.

I'm actually working on getting [first-class subview support](https://github.com/google/incremental-dom/pull/66) build into iDOM (but it won't apply to any of the other vDOM libraries). With it, no need to detach-reattach, just render. :racehorse: 

> render in Backbone combined with Backbone classes work quite differently from most vdom libraries.

That's because it's non-destructive in React. React's `#render` is very much like Backbone's `#template` (have we standardized that yet?). Where, Backbone's `#render` is a component concern in React and not for the dev to directly call.

**Comment by akre54** [comment]
> I treat it the same way I do subviews with jQuery: detach, render, reattach 

But... that triggers reflows, no? Isn't the performance worse than not using a vdom library at all?

Subview management is a hard problem in Backbone but it isn't unsolvable. But it's pretty at-odds with a tree-based descriptor approach that most vdom libraries take.

> Where, Backbone's #render is a component concern in React and not for the dev to directly call.

You could set up something similar in Backbone. The problem that creating a Backbone View typically has side-effects and isn't idempotent in the way vdom components are typically implemented. It could be done, but I have a feeling it'd be a lot easier just to use a vdom-first approach.

**Comment by jridgewell** [comment]
> But... that triggers reflows, no? Isn't the performance worse than not using a vdom library at all?

@jmeas and I actually did some [testing](https://github.com/jmeas/dom-op-tester) a while ago, and found that DOM manipulations that happen very quickly one-after-the-other don't have a huge reflow penalty. I think the browser will group them into a single reflow. No idea where the limit is, though.


The virtual DOMs (iDOM included) can actually trigger dozens of "reflows" in a single render, since all the elements are being modified _in_ the attached DOM tree. A few more to detach-reattach subviews doesn't hurt.

- - -

**Aside:** So one of the reasons iDOM is so damn fast is because it's optimizing for garbage collection over DOM manipulations. The manipulations are certainly slower than normal JS, so React was definitely on the right track. It's actually not the manipulations that was causing the bottleneck, but throwing away _hundreds_ of DOM instances. Think of all the Elements and Attribute instances that get created and thrown away doing `this.el.innerHTML = html`. _That's_ the bottleneck.

React intelligently diffs, so the largest source of garbage has been fixed. But, it still suffers from rendering out an entire virtual tree and then throwing away the old one.

```js
      var newTree = render(count);
      var patches = diff(tree, newTree);
      tree = newTree;
```

What iDOM has discovered is away to eliminate that virtual tree, and with it the last painful GC.

- - -

> But it's pretty at-odds with a tree-based descriptor approach that most vdom libraries take.

So what I've found is something like:

```mustache
<div>
  {{! some content }}
  <div id="subview"></div>
</div>
```

When you attach the subview, you entirely replace the `#subview` element. When it's time to re-render, you replace `subview.el` with the original element, and re-render. That'll maintain the `#subview` element in the tree. Now, just replace it again with `subview.el`.

**Comment by akre54** [comment]
> @jmeas and I actually did some testing a while ago, and found that DOM manipulations that happen very quickly one-after-the-other don't have a huge reflow penalty.

Knowing some (but not a ton) about performance optimization, I'd say that doesn't seem like removing and re-adding thousands of times scales to a large app. It's been the [recommendation of most of the browser vendors](https://developers.google.com/speed/articles/reflow) I've seen to avoid touching the DOM when you don't have to. 

I'm also not sure that repo shows the best methodology to test DOM performance. MutationObserver wasn't really meant to be used in that way. Maybe [Chromium's telemetry](https://www.chromium.org/developers/telemetry) or Firefox's performance tools (Topcoat has a pretty awesome [telemetry tool](https://github.com/topcoat/topcoat/tree/master/dev/test/perf/telemetry) built on Chromium) would be more suited.

> The virtual DOMs (iDOM included) can actually trigger dozens of "reflows" in a single render, since all the elements are being modified in the attached DOM tree.

This seems at odds with what you said above? One of the stated benefits of the virtual DOM is batching and then flushing changes all at the same time. Simply updating most properties won't trigger a reflow, adding and removing elements ([updating classNames, getting computed styles, etc.](http://www-archive.mozilla.org/newlayout/doc/reflow.html)) will.

We've gotten a little offtopic here (my fault), but I'd be happy to continue on Gitter.

**Comment by jridgewell** [comment]
> adding and removing elements (updating classNames, getting computed styles, etc.) will.

That's what I meant. Hopefully you're not adding and removing a bunch of elements every render, but updating classes is very common.

[Gitter](https://gitter.im/jashkenas/backbone?at=55db809c04a6730031627f0c) it is. :smile:

**Comment by jridgewell** [comment]
PS: I [forked](http://jsfiddle.net/fwdna26c/3/) a [fork](http://jsfiddle.net/jhohlfeld/cS66g/light/) of @jashkenas [Backbone v Ember](http://jsfiddle.net/jashkenas/CGSd5/) performance demo to add Backbone + Incremental DOM. It's stunningly fast. http://jsfiddle.net/fwdna26c/3/

**Comment by mr47** [comment]
@jridgewell maybe Incremental DOM have a future in backbone ?

**Comment by jashkenas** [comment]
@jridgewell — Very, very cool. Do you have any ambitions, or see any opportunities for integrating Backbone and Incremental DOM further?

**Comment by jridgewell** [comment]
Beside promoting it as the de-facto templating language (:wink:), I don't think there's anything to be done. For the majority of use cases, it's exactly analogous to using `_.template`:

```html
<script type="_/template" id="template">
  <div class="box" id="box-<%= number %>" style="top: <%= top %>px; left: <%= left %>px; background: rgb(0,0,<%= color %>);">
    <%= content %>       
  </div>
</script>

<script>
underscore.viewTemplate = _.template(document.getElementById('template').text);
</script>

<!-- - - - -->

<script>
iDOM.viewTemplate = function(data) {
  IncrementalDOM.elementOpen('div', null, null, 'class', 'box', 'id', 'box-' + data.number, 'style', {
    top: data.top + 'px',
    left: data.left + 'px',
    background: 'rgb(0,0,' + data.color + ')'
  });
    IncrementalDOM.text(data.content);
  IncrementalDOM.elementClose('div');
}
</script>
```

It's not pretty to hand write, but myself and several others are [working on pre-compilation](https://github.com/google/incremental-dom#templating-languages) from X -> iDOM. If you're using `_.template`, you can just swap the build target from `_.template`'s compiled function to compiled iDOM, and continue to use the JST object (or however you're referencing your templates). Then just replace the jQuery or `innerHTML` part of your `#render` to use `iDOM.patch`:

```js
var View = Backbone.View.extend({
  template: underscore.viewTemplate,
  render() {
    this.$el.html(this.template(this.model.attributes));
    return this;
  }
});

// - - -

var View = Backbone.View.extend({
  template: iDOM.viewTemplate,
  render() {
    iDOM.patch(this.el, this.template, this.model.attributes);
    return this;
  }
});

**Comment by jashkenas** [comment]
> It's not pretty to hand write, but myself and several others are working on pre-compilation from X -> iDOM. If you're using _.template, you can just swap the build target from _.template's compiled function to compiled iDOM, and continue to use the JST object (or however you're referencing your templates). Then just replace the jQuery or innerHTML part of your #render to use iDOM.patch:

That's kind of what I'm hinting at. Perhaps (when iDOM templating language is ready), we should bake in a render function into backbone that sets all of that up for you? Just a thought.

**Comment by jridgewell** [comment]
We could certainly do that.
