### ISSUE TITLE
inconsistent events callback for 'all'

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3795]
As far as I can tell, this is a problem

```javascript
appEvents.on("all", function(eventName){
    console.log(eventName + ' was triggered!'); //works as expected
});

appEvents.on("something-else", function(eventName){
    console.log(eventName + ' was triggered!'); //nope!! not gonna work, eventName is not automatically available in callback as first argument
});
```

when you listen to all, the first arg is the event name

but when you listen to a specific event, the first arg is not the event name

this is bad

can it be fixed?

**Comment by ORESoftware** [comment]
yeah, I can confirm that this is really bad

**Comment by akre54** [comment]
`all` is a special event. We specifically [prepend the event name](https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L357) in the `all` callback so that you know what event it was called with. If you bind a listener to the `something-else` event you already know the event that triggered your listener. It's `something-else`.

**Comment by ORESoftware** [comment]
yeah, and to be consistent, the callbacks for each and every events should have the event name as the first parameter in the callback, IMO
