### ISSUE TITLE
delegateEvent documentation example is irrelevant

### ISSUE THREAD

**Issue by Ferixz** [jashkenas/backbone#3852]
Here's the [`delegateEvents` documentation](http://backbonejs.org/#View-delegateEvents) example code:

```javascript
var DocumentView = Backbone.View.extend({

  events: {
    "dblclick"                : "open",
    "click .icon.doc"         : "select",
    "contextmenu .icon.doc"   : "showMenu",
    "click .show_notes"       : "toggleNotes",
    "click .title .lock"      : "editAccessLevel",
    "mouseover .title .date"  : "showTooltip"
  },

  render: function() {
    this.$el.html(this.template(this.model.attributes));
    return this;
  },

  open: function() {
    window.open(this.model.get("viewer_url"));
  },

  select: function() {
    this.model.set({selected: true});
  },

  ...

});
```

This is the description of the example:
> A view that displays a document in a search result might look something like this:

I'm not sure how the code is related to the `delegateEvents` topic or the above description.

**Comment by akre54** [comment]
What's the confusion? The example is demonstrating how you'd lay out a view using the `events` hash (described earlier in that section), mapping DOM events to view methods. 

Backbone was extracted from [DocumentCloud](https://www.documentcloud.org), so that example may be a bit specific to DocumentCloud's use case. Do you have another example that you think would make more sense?

**Comment by Ferixz** [comment]
My bad. I'm not sure if I missed the first 4 paragraphs or it wasn't there yesterday! 
I was looking for `delegateEvent` keyword and the only thing explaining the usage was the code and the description I posted (or that's how I remember it anyways).
