### ISSUE TITLE
Backbone 1.3.2

### ISSUE THREAD

**Issue by jridgewell** [jashkenas/backbone#3975]
I'm making a mess of this release process.

Checklist for v1.3.2 (which is really v1.3.0):

- Update `Backbone.VERSION`
- Update version comment at the top of `backbone.js`
- `npm run build`
- Bump `package.json`
- Create changelog entries telling everyone I screwed up and these versions are really the same
- Update `gh-pages` branch
- Push to npm after someone confirms I'm not an idiot.

Anyone know of anything else I missed? @paulfalgout, @megawac, @akre54?

**Comment by akre54** [comment]
🙈

Minify / source map main backbone.js file, rebuild docco / docs

(Also the changelog release date on 1.3.0 is out of date, might wanna fix
that)

**Comment by paulfalgout** [comment]
There's also a comment at the top of the library containing the version

**Comment by jridgewell** [comment]
> Also the changelog release date on 1.3.0 is out of date, might wanna fix that

Yah, I'm just going to update the changelog to say `1.3.2` instead, so I'll update the date too.

> There's also a comment at the top of the library containing the version

Added.

**Comment by paulfalgout** [comment]
Nice!  Well now that you'll have done 3 releases you'll be an expert.

**Comment by jridgewell** [comment]
:stuck_out_tongue_winking_eye:

**Comment by megawac** [comment]
Also create git tag, either by `npm version patch` or `git tag`

**Comment by JSteunou** [comment]
FYI `npm version` + `npm scripts` hooks (pre|post version, pre|post publish) could help you a lot with that.

**Comment by jridgewell** [comment]
> FYI npm version + npm scripts hooks (pre|post version, pre|post publish) could help you a lot with that.

Yup, I'm going to work on that after I do this one.

**Comment by elgubenis** [comment]
the feature release broke something in our development environment, we are using marionette though and that might be an issue, seems like the backbone collections are not correctly triggering events to the collectionveiw after fetching, but need to investigate more to be sure

**Comment by paulfalgout** [comment]
Marionette has a fixed version dependency on backbone. Since Bb isn't using semver, it requires we manually update Marionette with every release.  So if you've updated your Bb dependency locally, and you're using a package manager, you're actually using a different copy of Backbone than Marionette is.

**Comment by elgubenis** [comment]
we are omitting the fixed version for marionette, in our environment marionette always uses the latest backbone version, that might be the issue

**Comment by megawac** [comment]
Also you gotta update the `index.html` whenever you create a release. See https://github.com/jashkenas/backbone/commit/d682061a25f72ab82fbda472d229cc3d1da7df2b

**Comment by davis** [comment]
why doesn't backbone follow semver? :( i lost so much time debugging this

**Comment by paulfalgout** [comment]
@davis https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by akre54** [comment]
Also gotta run `npm run doc` to rebuild the docs pages

**Comment by jdalton** [comment]
@davis
> why doesn't backbone follow semver? :( i lost so much time debugging this

I wasn't aware there was breaking changes.
:+1: for documenting them in the [changelog](https://github.com/jashkenas/backbone/pull/3921/files). 
Was Marionette relying on undocumented or edge behavior.

**Comment by paulfalgout** [comment]
Actually no, as far as I am aware there are no breaking changes.  Historically Marionette has locked down the dependency on Backbone because Marionette does follow semver, so we wanted no surprises if Backbone or Underscore updated a patch with a breaking change as with Underscore 1.7 for instance.

However I personally don't think that's working out and am suggesting backbone/underscore be set as a peer dependency https://github.com/marionettejs/backbone.marionette/issues/2909 for all related "plugins"

Essentially the problems people have been running into have arisen from upping their project's backbone/underscore dependency only to find Marionette is still using a 2nd copy of the older version.

**Comment by onehorsetown** [comment]
The change in Backbone 1.3.1 that "broke" Marionette may have impact outside of the Marionette ecosystem:

https://github.com/jashkenas/backbone/commit/00f5c39e2784602f89f4f036323ba3688ee45af4

Marionette makes this call:

```
this.once('render', this._initialEvents);
```

Notice no context (third parameter) is specified.  In BB 1.2.3 the context defaulted to the 'this' pointer of the call.   As of Backbone 1.3.1, the context defaults to the callback itself.  This seems like a pretty major behavioral change that might break a lot more than just Marionette.

As far as I can trace, Events.once used to call eventsApi with 'void 0' as the callback.  As of Backbone 1.3.1,  the callback is passed directly through.   This is all well and good until you look at line 144:

```
      if (callback !== void 0 && 'context' in opts && opts.context === void 0) opts.context = callback;
```

As of Backbone 1.3.1, the callback is no longer "void 0" and the context is now defaulting to the callback itself.   In Backbone 1.2.3 the context (that is, the ctx value of the callback object) would default to the this pointer of of the original call:

```
      handlers.push({ callback: callback, context: context, ctx: context || ctx, listening: listening });
```

Sorry if my explanation is convoluted.  I can't pretend to understand all of the internal machinations of the Backbone event system.  I simply do know that Marionette is not working with Backbone 1.3.1.   Your answer above was to continue using Marionette with Backbone 1.2, and that is fine.   However, I simply wanted to bring up the possibility that the underlying issue is more pervasive.

**Comment by elgubenis** [comment]
@onehorsetown thank you, thats exactly the problem we were facing. i guess there is no test for the scope of this there.

**Comment by jridgewell** [comment]
I'll wait for this fix before doing 1.3.2.

**Comment by megawac** [comment]
I wasn't able to reproduce this issue locally @elgubenis https://github.com/megawac/backbone/commit/2f2804e5799c3e47220e88f820ba1dfc175b69ee can you create a failing test case?

**Comment by jdalton** [comment]
Is 1.3.2 ready?

**Comment by salex772** [comment]
I tried 1.3.2 but the same. Only backbone 1.2.0 and marionette 2.4.3 works. All other combinations I have tried do not work.

**Comment by paulfalgout** [comment]
Marionette does not yet support 1.3.2

**Comment by akre54** [comment]
Can we do a smoke test against the top 5 or so plugins before releases? I
feel like we did this at one point.

On Sun, Mar 13, 2016, 19:26 Paul Falgout <notifications@github.com> wrote:

> Marionette does not yet support 1.3.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jashkenas/backbone/issues/3975#issuecomment-196080615>
> .
>
-- 

Adam K (mobile)
