### ISSUE TITLE
setting root Backbone.History.Start not working with cordova?

### ISSUE THREAD

**Issue by benmcmaster** [jashkenas/backbone#4048]
I recently upgraded from Backbone 1.1.2 to 1.3.3. I noticed that my cordova app stopped working. It couldn't start the router. I tracked it down to ```Backbone.history.start({root: "/app/"})```. When I remove the ```{root: "/app/"}``` it starts the router just fine. Before the upgrade adding the root just magically worked even though my cordova app was just at index.html#. What changed? Is there a work around?

**Comment by akre54** [comment]
I'm not familiar with Cordova specifically, but this is the [diff between 1.1.2 and 1.3.3](https://github.com/jashkenas/backbone/compare/1.1.2...1.3.3).

It looks like we changed behavior around trailing slashes on root (feel free to look up the pull request if you're interested). Maybe try it without the trailing slash? So `/app` instead of `/app/`.

**Comment by benmcmaster** [comment]
@akre54 Thanks for the reply! I see the changes around trailing slashes in previous commits. I am not sure if that is affecting my issue. It might.

I tried:
```
Backbone.history.start({root: "/app"})
```
and
```
Backbone.history.start({root: "app"})
```
Both failed at finding the initial route of "". ```Backbone.history.start``` returns ```false```. So it's still not working for me.

Truthfully, I don't know much about how cordova web views are different from normal browsers. Here is a good guide to webviews in Cordova:

http://developer.telerik.com/featured/what-is-a-webview/

So when I track the ```window.location.href``` in my app I see (iOS):
```
file:///var/containers/Bundle/Application/DE104444-D1A4-4B41-A144-06ECEBFB4444/AppName.app/www/index.html
```
When I navigate to a different page:
```
file:///var/containers/Bundle/Application/DE104444-D1A4-4B41-A144-06ECEBFB4444/AppName.app/www/index.html#more
```
This is a cross platform app so the web version is also located on my server at myapp.com/app. And for the web I use:
```
Backbone.history.start({pushState: true, root: "/app/"})
```
to start the app. This setup is nice because the deeplinks are shared. For example, the cordova app a link to ```mycustomurl://app/more``` takes me to ```index.html#more```.  ```/app``` is ignored. This is the current behavior in Backbone 1.1.2... which is convenient. 

Does that help you understand? I would love to figure this out. Until then I can't upgrade backbone. :(

**Comment by akre54** [comment]
Sorry -- I'm not super familiar with Cordova. You might have better luck on StackOverflow or a Cordova-specific mailing list / IRC channel.

I could be wrong but I think your root is actually `file:///var/containers/Bundle/Application/DE104444-D1A4-4B41-A144-06ECEBFB4444/AppName.app/www/`, rather than `/app`. Our history object uses [`window.location`](https://github.com/jashkenas/backbone/blob/v1.3.0/backbone.js#L1603) in several places to determine the canonical location, so you'd probably want to make sure that and your app are in sync.

If there's something we can change in Backbone to make it easier to work with Cordovoa, please let us know. Otherwise I'm going to close this for now.

**Comment by benmcmaster** [comment]
Thanks for looking into it, Adam. I will post on Stack Overflow.
