### ISSUE TITLE
Collection#create returns model that was created, why not follow the convention that model#save returns?

### ISSUE THREAD

**Issue by reidcooper** [jashkenas/backbone#4052]
I have been recently learning Backbone and Marionette and I've thankfully getting the hang of it. Very nice implementation.

Anyways, I was curious on why collection#create returns the model that was created where as model#save returns a jqXHR as per the docs. Is there something similar that does the same? I was hoping that the convention would be the same, but I understand that collection#create, as the docs state, "Equivalent to instantiating a model with a hash of attributes, saving the model to the server, and adding the model to the set after being successfully created. Returns the new model. If client-side validation failed, the model will be unsaved, with validation errors." If the model was successfully created and added to the collection, why does it return the model created and not the jqXHR when a model was successfully saved? 

This was brought to my attention when I was trying to handle some asynchronous responses on collection model creation. I was having issues waiting for the model to be created in the same fashion as I handle the jqXHR on model#save upon success by using $.when(call). Instead, I have to pass in a success and fail options params to the collection#create method in order to receieve a proper callback. I'm sure having two ways it not that big of the deal however I was hoping for some understanding on the difference. Otherwise, would it be possible to return the jqXHR of the model being returned? Or in another fashion perhaps?

**Comment by namdets** [comment]
The way I use it, there are two scenarios when I would call create on a collection:
- I am creating a new instance of a transient model in a client side only collection.
- I am creating a new instance of a persistent model in a collection that is saved on the server.

I use the first scenario frequently when I am prototyping an application. This does result in the URL must be set error in the console, but returns me a useful model to work with. A jqXHR does not preserve 

Also if I wish to allow the user to create a collection of related models during the process of creating a 'parent' model, I may require the 'parent' model to be saved before the URL for the collection is known, but the create may still want to be called for each related model to invoke validation and so that a final sync after setting the URL will persist the entire collection successfully.

I would only ever call save on a model directly if I intend for it to be sent to the server, so a jqXHR is appropriate. 

Also, when you call save on a model you already have a local reference to the model that you are saving, so the jqXHR is additional information. If calling create on a collection returned only a jqXHR, you would not have a reference to the model that is in the collection(see line 1113 in the dev version source) if you passed a regular attribute hash to create, only the reference to the hash that you passed in which is not the model. 

Maybe the best thing would be to have collection#create continue to function as is and add another function collection#save which requires an initialized model but returns a jqXHR.

**Comment by reidcooper** [comment]
It makes sense as to why collection#created was added, to help a couple workflows together. I wish however that there could be perhaps a consistency between the two. I want the shortcut but I want the jqXHR, so I guess I can't have my cake and eat it too? I am not sure. What you said @namdets makes a lot of sense as well. So in my case I could just use model#new and then pass in that model to collection#model_save or whatever, to actually return the jqXHR as well as adding that model to the collection.
