### ISSUE TITLE
Collection's byId lookup is used inconsistently

### ISSUE THREAD

**Issue by crgee** [jashkenas/backbone#4102]
The typical behavior for `byId` is to store a model by `id` as determined by the model's implementation of `modelId` and/or by `cid` (for Backbone's convenience) . In most places this is fine, except for here:

https://github.com/jashkenas/backbone/blob/153dc41616a1f2663e4a86b705fefd412ecb4a7a/backbone.js#L996

The issue here is that by using `obj` to access `byId`, `obj` is effectively bypassing access with `id` which should have higher priority considering it is the documented methodology: http://backbonejs.org/#Collection-modelId.

`id` and `cid` should have precedent over `toString`. Anyone who inadvertently implements `toString` to create collisions may have an interesting time determining how they suddenly have missing or merged models within their collections.

**Tested here: https://jsfiddle.net/5kn7vqx0/5/**

Now - I am willing to concede my scenario is peculiar but the change is both small and more accurate to the documentation.

**Comment by jridgewell** [comment]
I think we had a PR that tested the type of `obj` before trying to use it as the key...

**Comment by crgee** [comment]
I am uncertain what to do to proceed - I referenced master, so a PR hasn't changed anything yet. Even with a check, it would be inappropriate to use a model's `toString` in advance of `modelId`.

**Comment by jgonggrijp** [comment]
The intent of that line is not to perform `obj.toString()`, but to cater to scenarios where `obj` is a string (or number) already. You are supposed to be able to do `collection.get('1')`. I don't think there is anything strange about prioritizing this over the `id` and the `cid`, especially given that it is cheaper.

I think your fiddle demonstrates a rather exotic corner case where a heterogeneous collection, combined with an overridden `toString` method on the model prototype, leads to a problematic situation. In addition, the "workaround" in your fiddle actually seems very acceptable to me. It makes `toString` more informative, and consistent with `Collection.modelId`. If you want only the id, you can already do `model.id`. You can also factor out the common logic between `WorkAround.toString` and `Collection.modelId` to make it DRY.

While I don't know your use case, I should add that I find overriding `toString` on a model class questionable. `toString` is sensitive stuff, as it has a special meaning to the JS engine, so overriding it shouldn't be taken lightly.

Your problem could theoretically be fixed by changing the line in question to this:

```js
      return typeof obj !== 'object' && this._byId[obj] ||
```

but this would only fix your particular corner case, while potentially breaking somebody else's exotic corner case. It would also add to the complexity of the code. As you can tell, I'm not in favor, but you can monkey-patch Backbone as follows if you really want to have a `Model.toString` that is inconsistent with `Collection.modelId`:

```js
var originalGet = Backbone.Collection.prototype.get;

Backbone.Collection.prototype.get = function(obj) {
    return originalGet.call(this, obj instanceof Backbone.Model ? obj.attributes : obj);
};
```

I will close this now, but feel free to comment if you think I'm missing something.
