### ISSUE TITLE
updating a model in a collection with Collection.create( ,merge: true) updates the backend with only the new attributes

### ISSUE THREAD

**Issue by rianwouters** [jashkenas/backbone#4172]
Consider a model m with id 0 and attributes { a: 10 } in a collection c

now do c.create({ id: 0, b: 20}, { merge: true })

it's supposed to update the model and save it.

the resulting model indeed has attributes: { a: 10, b: 20}
however, the RESTful PUT has only { b:20 }
Following the definition of PUT, it will replace the content of the resource with the new content,
which is { b: 20}

For PATCH this is Ok, but for UPDATE you need to put the merge attribute list.

One way to solve this, is to save the merged model (returned by add) iso the temporarily created model.
However, this will be more complicated with the combination with options.wait

A workaround is to use the patch option.

**Comment by paulfalgout** [comment]
I the issue here is that `create` is for `POST`ing  From the docs "The create method can accept either an attributes hash or an existing, unsaved model object."  _unsaved_ meaning there is no id.  You should not `create` with an id.  `create` is expecting an `id` to be returned from the server.  If anything `create` should error if it finds an `idAttribute`

**Comment by rianwouters** [comment]
I see the point.

For completeness sake, my workaround: 

(get(id) || add({id})).save(attrs)
