### ISSUE TITLE
Bug: Backbone anything that has URI encoded characters (spaces and quotation marks) in the fragment triggers loadUrl twice in the navigate function

### ISSUE THREAD

**Issue by tsangjustin** [jashkenas/backbone#4188]
When I pass URI encoded characters such as spaces and quotation marks into the fragment navigate will decode the fragment and store that in this.fragment. When checkUrl is later on triggered it will detect that the fragment has changed even though it hasn't the encoded and decoded version of the fragment is compared and makes them not equal. This causes loadUrl to be triggered and load the encoded version of the fragment.

**Comment by jarstelfox** [comment]
@tsangjustin,

Which browser are you using?

Exabeam's comment on #4132 [explains what is happening in depth.](https://github.com/jashkenas/backbone/issues/4132#issuecomment-350920374) gwynjudd on #4175 mentioned the url encoding changed in [chrome 63 (Released Dec 2017)](https://www.insightportal.io/desktop-browsers/1476-chrome-63-release-date-and-features) changed, which lines up with the recent influx of comments on tickets:
- #4132
- #4175
- #3399

However, it also seems this may have existed in Firefox (due to comments on the mentioned tickets), however, I have not tested at this time.

sjmiller85 [wrote a workaround for this issue.](https://github.com/jashkenas/backbone/issues/3399#issuecomment-245582726)
