### ISSUE TITLE
There is a reference error in the trigger event

### ISSUE THREAD

**Issue by ys-yancy** [jashkenas/backbone#4211]
When I am off event,  the events in the trigger function can't be synchronized, because the var events = this._events[name] statement in the trigger function is wrong, this._events[name] = retain = in the off function. The var events = this._events[name] in the [] statement and the trigger function are two different reference addresses.

The trigger function should be changed to:
```
trigger: function(name) {
      if (!this._events) return this;
      var args = slice.call(arguments, 1);
      if (!eventsApi(this, 'trigger', name, args)) return this;

      //var events = this._events[name];

      var allEvents = this._events.all;
      if (this._events[name]) triggerEvents(this._events[name], args);
      if (allEvents) triggerEvents(allEvents, arguments);
      return this;
    },
```

**Comment by paulfalgout** [comment]
perhaps a codepen or jsfiddle reproducing the error would help

**Comment by taburetkin** [comment]
> perhaps a codepen or jsfiddle reproducing the error would help

actually, i told about this issue very long ago.
i faced with it when i occasionally pass to the view something wrong instead of a collection.
everything in a view works fine until `stopListening`

but here is the link: https://codepen.io/dimatabu/pen/gyVVBz?editors=1010
```
const listener = _.extend({}, Backbone.Events);
const something = {};
listener.listenTo(something, 'some:event');
listener.stopListening(something);
console.log('no errors');
```

under the hood there is an `off` call:
```
  Events.stopListening = function(obj, name, callback) {
    var listeningTo = this._listeningTo;
    if (!listeningTo) return this;

    var ids = obj ? [obj._listenId] : _.keys(listeningTo);

    for (var i = 0; i < ids.length; i++) {
      var listening = listeningTo[ids[i]];

      // If listening doesn't exist, this object is not currently
      // listening to obj. Break out early.
      if (!listening) break;

      listening.obj.off(name, callback, this); // <-- at this place obj without events mixin will fail.
    }

    return this;
  };
```

i don't know which behavior should be
swallow, throw on events registration or on event stop listening
but, i believe something should happens
for me its good to throw on event registration if given object is not supports events.
