### ISSUE TITLE
Query parameters are confusing the router

### ISSUE THREAD

**Issue by martynsmith** [jashkenas/backbone#891]
It is not currently possible to use Google Analytics with backbone controlled routes, as the backbone router does not understand query parameters. If I have the routes:

``` javascript
routes: {
    "": "index",
    ":username": "profile",
}
```

then try to route to `martyn?utm_source=google&utm_medium=ppc&utm_term=testing`, the profile route fires but the username passed is `martyn?utm_source=google&utm_medium=ppc&utm_term=testing` rather then `martyn`.

I saw the discussion on #668. I don't need query parameter support per se, but it would be nice if backbone could be told to ignore query parameters.

For now I've done (in my own code):

``` javascript
(function(old) {
    Backbone.History.prototype.getFragment = function() {
        return old.apply(this, arguments).replace(/\?.*/, '');
    };
})(Backbone.History.prototype.getFragment);
```

**Comment by bweston92** [comment]
I've just come across this issue my-self, how is this even desired behavior? The query string shouldn't be part of what is sent to my router callback.

**Comment by braddunbar** [comment]
Why is that? I've found the querystring to be a very useful thing to have in router callbacks.

**Comment by bweston92** [comment]
Not when I'm expecting an optional `id` parameter.

**Comment by bweston92** [comment]
For example:
I have some routes that are matching on query parametres:
```
appRoutes:
    'deals/offers': 'listOffers'
    'deals/:deal_id/offers': 'listOffers'
```

Using the route /deals/offers?status=REJECTED this is what is being passed to listOffers
```
listOffers: (dealId) ->
    # dealId = "status=REJECTED"
```

**Comment by braddunbar** [comment]
Ah, yes. Try this instead:

```coffee
routes:
  'deals(/:deal_id)/offers': 'listOffers'
```

You'll get two arguments every time instead of a variable number.

**Comment by bweston92** [comment]
But surly this default functionality isn't desired, who would want a query string passed if expecting an id?

**Comment by braddunbar** [comment]
Well, the router certainly doesn't know what you're expecting. :smiley: Only that you gave it the same function to call for two routes with a different number of parameters. You can also remove the query string entirely by overwriting `Router#execute`.

```js
execute: function(callback, args) {
  args.pop()
  if (callback) callback.apply(this, args)
}
```

**Comment by online-java-training** [comment]
Hello,

I have one similar problem

GET http://localhost:8956/api/Course/GetCourseDetailsById/Node.JS-Training 

The above URL says 404. I think it is because of . (Dot) param value

 (Not Found)send @ jquery-2.1.4.js:8630jQuery.extend.ajax @ jquery-2.1.4.js:8166jQuery.(anonymous function) @ jquery-2.1.4.js:8311jQuery.extend.getJSON @ jquery-2.1.4.js:8294wisen.PageContentView.Backbone.View.extend.render @ WisenJS.js:66wisen.WisenRoute.Backbone.Router.extend.processMenuSelection @ WisenJS.js:130_.extend.execute @ backbone.js:1265(anonymous function) @ backbone.js:1254(anonymous function) @ backbone.js:1481_.some._.any @ underscore.js:258_.extend.loadUrl @ backbone.js:1479_.extend.navigate @ backbone.js:1530(anonymous function) @ WisenJS.js:122jQuery.event.dispatch @ jquery-2.1.4.js:4435elemData.handle @ jquery-2.1.4.js:4121

<a href="http://javascripttrainingcourses.com/JS-Courses/BackboneJS-Training" title="Backbone.js Training">Backbone.js Training</a>
