### ISSUE TITLE
Just like 'set' has {silent:true}, add a {force:true} option

### ISSUE THREAD

**Issue by micros123** [jashkenas/backbone#944]
In our current project we are more than once running into the situation where a value is set, but the value is identical to the previous value. This makes the chain of events come to a halt.
This happens for example when calling a server with a second search query, which also has zero results. So the first time you have zero results, it could trigger some user feedback, but the second time, it won't work.
Of course it is possible to set the value twice, passing a random value first, with the silent parameter, and the second time the real results.
But a way to force the Event would be much more elegant and in line with the {silent:true} functionality.

Thank you for any feedback on this!

**Comment by hardboiled** [comment]
@jashkenas I wouldn't write off a need to know whether a model has been set to a valid data set that happened to already match the data in the model. In my application, I have a member that's loaded at login. Our application requires that we be able to ship products to them, so we need to make sure that they have real information in their account. Thus, we walk them through some steps to verify their data.

The UX chosen has only one button on the design that advances through each section (e.g. first name/last name to the address section). The model is filled out in piecemeal due to there being only one aggregate endpoint for member data. Thus, multiple views map to this one model and the model info is collected in steps until the confirmation step that actually sends the entire dataset to the back-end. I chose to control transitions between steps by listening on the "change" event and a custom event by overriding "set" whose purpose is to prevent the UI from locking up if the user is satisfied with the existing data we have and just opts to click the "next" button without changing the model.

I'm not requesting this feature to be added, but it was a need that I needed to address for my purposes. Thanks for making a great library for the public to consume.

It looks like this in coffee script:

    set:(attrs,options)->
      willChange = false
      for k,v of attrs
        willChange = willChange || @attributes[k] != v
      if willChange then super(attrs,options)
      else @trigger('set-no-change')
